on: [push, pull_request, workflow_dispatch]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache west modules
        uses: actions/cache@v3
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (corne Left)
        run: west build -s zmk/app -b nice_nano -- -DSHIELD=corne_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Check build status
        run: |
          if [ -f "build/zephyr/zmk.uf2" ]; then
            echo "Build successful. zmk.uf2 file found."
          else
            echo "Build may have failed. zmk.uf2 file not found."
            exit 1
          fi
      - name: corne DTS File
        if: always()
        run: |
          if [ -f "build/zephyr/nice_nano.dts.pre.tmp" ]; then
            cat -n build/zephyr/nice_nano.dts.pre.tmp
          else
            echo "DTS file not found. Listing build directory contents:"
            ls -R build
          fi
      - name: corne Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corne_left_nice_nano.uf2
      - name: Archive (corne Left)
        uses: actions/upload-artifact@v4
        with:
          name: firmware-left
          path: corne_left_nice_nano.uf2
      - name: West Build (corne Right)
        run: west build --pristine -s zmk/app -b nice_nano -- -DSHIELD=corne_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Check build status (Right)
        run: |
          if [ -f "build/zephyr/zmk.uf2" ]; then
            echo "Build successful. zmk.uf2 file found."
          else
            echo "Build may have failed. zmk.uf2 file not found."
            exit 1
          fi
      - name: corne Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2 (Right)
        run: cp build/zephyr/zmk.uf2 corne_right_nice_nano.uf2
      - name: Archive (corne Right)
        uses: actions/upload-artifact@v4
        with:
          name: firmware-right
          path: corne_right_nice_nano.uf2